# Generated by Django 4.2.4 on 2023-09-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('stockiest_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('pcontain', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
    ]
